# Configurações que valem para TODOS os profiles
auth:
  jwt:
    secret: "GvB8kL9pQ3wR7uT2yX5zA8nF6mH4tK1b"
    expirationMs: 3600000
    refreshExpirationMs: 604800000

server:
  port: 8080

spring:
  profiles:
    active: dev
  # CONFIGURAÇÃO DO FLYWAY (Global)
#  flyway:
#    enabled: true
#    baseline-on-migrate: true  # <--- ISSO PROTEGE SEUS DADOS NO ORACLE
#    baseline-version: 1
#    locations: classpath:db/migration

---
# DEV — ORACLE LOCAL
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    username: ROOT
    password: root123
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: validate
    show-sql: true

---
# DOCKER — ORACLE FORA DO CONTAINER (Via Host)
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:oracle:thin:@host.docker.internal:1521/XEPDB1
    username: ROOT
    password: root123
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: validate
    show-sql: true

---
# PROD — POSTGRES AWS
spring:
  config:
    activate:
      on-profile: dev # ---> mudar para prod quando necessario ir para produção
  datasource:
    url: jdbc:postgresql://db-projeto-piloto.cg90g0iomqah.us-east-1.rds.amazonaws.com:5432/postgres
    username: postgres
    password: c6vOzOH-Z_8*f3Y>f1i7be2w]P9n
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update # Em prod o Flyway cria, mas o Hibernate pode atualizar se necessário
    show-sql: false
