apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: default
data:
  default.conf: |
    server {
        listen 80;
        
        error_log  /var/log/nginx/error.log notice;
        access_log /var/log/nginx/access.log;

        # Rota para o Swagger e Root
        location / {
            proxy_pass http://projeto-piloto-svc:80; 
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Rota para o Front-end Angular consumir a API
        location /api/ {
            proxy_pass http://projeto-piloto-svc:80/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
