name: CI/CD Projeto Piloto - EKS Fargate

on:
  push:
    branches:
      - develop   # branch que dispara o deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      #  Checkout do código
      - name: Checkout código
        uses: actions/checkout@v4

      #  Login no Docker Hub
      - name: Login Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      #  Build da imagem Docker
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/projeto-piloto:latest .

      #  Push da imagem para Docker Hub
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/projeto-piloto:latest

      #  Configurar credenciais AWS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      #  Atualizar kubeconfig
      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --region $AWS_REGION --name ${{ secrets.EKS_CLUSTER_NAME }}

      #  Deploy para Kubernetes (EKS Fargate)
      - name: Deploy to Kubernetes
        run: |
          DEPLOYMENT_NAME=projeto-piloto
          kubectl set image deployment/$DEPLOYMENT_NAME $DEPLOYMENT_NAME=${{ secrets.DOCKER_USERNAME }}/projeto-piloto:latest
          kubectl rollout status deployment/$DEPLOYMENT_NAME
